spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vendor_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
external-api:
  url: "https://api.vendor.com/data"